services:
  postgres-db:
    image: postgres:15-alpine
    container_name: biometric_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=minhasenhasegura
      - POSTGRES_DB=gestao_biometrica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: