# Configuração da ligação ao PostgreSQL no Docker (Atualizado)
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_biometria_db
spring.datasource.username=paulo_admin
spring.datasource.password=uan_senha_123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate / JPA
# O 'update' vai ler as tuas classes Java e criar as tabelas automaticamente no Docker!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

